name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run make setup
        run: make setup

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test